spring.application.name=todo-backend
spring.datasource.url=jdbc:postgresql://localhost:5432/learning
spring.datasource.username=Your username
spring.datasource.password=Your DB password

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true